# Generated by Django 4.2.7 on 2025-06-11 12:07

from django.db import migrations, models
import tyres.models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rimmodel',
            name='image',
            field=models.ImageField(default=tyres.models.get_default_rim_image, upload_to='rims/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rimvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('silver', 'Серебристый'), ('black', 'Черный'), ('grey', 'Серый'), ('white', 'Белый'), ('bronze', 'Бронзовый'), ('custom', 'Другой')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='rimvariant',
            name='material',
            field=models.CharField(choices=[('forged', 'Кованый'), ('cast', 'Литой'), ('stamped', 'Штампованный'), ('other', 'Другой')], max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='tyremodel',
            name='image',
            field=models.ImageField(default=tyres.models.get_default_tyre_image, upload_to='tyres/', verbose_name='Изображение'),
        ),
    ]
