# Generated by Django 4.2.7 on 2025-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_alter_rimmodel_image_alter_rimvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='favouriterim',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='favourite',
            name='tyres_favou_user_id_12fd60_idx',
        ),
        migrations.RemoveIndex(
            model_name='favouriterim',
            name='tyres_favou_user_id_5e98d5_idx',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='favouriterim',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user', 'created_at'], name='tyres_favou_user_id_3d1e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['variant'], name='tyres_favou_variant_82d3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriterim',
            index=models.Index(fields=['user', 'created_at'], name='tyres_favou_user_id_4c03f2_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriterim',
            index=models.Index(fields=['rim_variant'], name='tyres_favou_rim_var_3f4951_idx'),
        ),
    ]
