# Generated by Django 4.2.7 on 2025-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0003_alter_favourite_options_alter_favouriterim_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='favouriterim',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='favourite',
            name='tyres_favou_user_id_3d1e1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='favouriterim',
            name='tyres_favou_user_id_4c03f2_idx',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='favouriterim',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user', 'added_at'], name='tyres_favou_user_id_12fd60_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriterim',
            index=models.Index(fields=['user', 'created'], name='tyres_favou_user_id_5e98d5_idx'),
        ),
    ]
