# Generated by Django 4.2.7 on 2025-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_alter_favourite_options_alter_favouriterim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rimmodel',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='tyremodel',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
