# Generated by Django 4.2.7 on 2025-06-11 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0005_rimmodel_release_year_tyremodel_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreTTX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('tread_depth', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Глубина протектора (мм)')),
                ('noise_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(80)], verbose_name='Уровень шума (дБ)')),
                ('wet_grip', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Сцепление с мокрой дорогой')),
                ('rolling_resistance', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Сопротивление качению')),
                ('max_load', models.IntegerField(verbose_name='Максимальная нагрузка (кг)')),
                ('reinforced', models.BooleanField(default=False, verbose_name='Усиленная')),
                ('run_flat', models.BooleanField(default=False, verbose_name='Run Flat')),
                ('tyre_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttx_variants', to='tyres.tyremodel')),
            ],
            options={
                'verbose_name': 'ТТХ шины',
                'verbose_name_plural': 'ТТХ шин',
            },
        ),
        migrations.CreateModel(
            name='RimTTX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('load_capacity', models.IntegerField(verbose_name='Грузоподъемность (кг)')),
                ('hub_bore', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Диаметр центрального отверстия (мм)')),
                ('spoke_count', models.IntegerField(verbose_name='Количество спиц')),
                ('finish_type', models.CharField(choices=[('painted', 'Окрашенный'), ('polished', 'Полированный'), ('machined', 'Фрезерованный'), ('chrome', 'Хромированный'), ('powder_coated', 'Порошковая окраска')], max_length=50, verbose_name='Тип покрытия')),
                ('is_flow_formed', models.BooleanField(default=False, verbose_name='Flow Forming технология')),
                ('has_lip', models.BooleanField(default=False, verbose_name='Наличие полки')),
                ('rim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttx_variants', to='tyres.rimmodel')),
            ],
            options={
                'verbose_name': 'ТТХ диска',
                'verbose_name_plural': 'ТТХ дисков',
            },
        ),
    ]
